<!-- Wheels -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Wheel dimensions -->
    <xacro:property name="wheel_radius" value="${car_height / 2.0 + wheel_joint_z + ground_height}"/>
    <xacro:property name="wheel_width" value="0.3"/>

    <!-- Wheel offsets -->
    <xacro:property name="wheel_joint_x" value="${car_length / 2.0 - 0.4}"/>
    <xacro:property name="wheel_joint_y" value="${car_width / 2.0 + wheel_width/ 2.0 + 0.1}"/>
    <xacro:property name="wheel_joint_z" value="-0.2"/>

    <!-- Color -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 0.7"/>
    </material>

    <!-- Wheel geometry -->
    <xacro:macro name="wheel_geometry" params="wheel_name">
        <link name="${wheel_name}">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin rpy="${PI / 2.0} 0.0 0.0"/>
                <material name="black"/>
            </visual>
        </link>
    </xacro:macro>

    <!-- Rear wheel function -->
    <xacro:macro name="wheel_rear_func" params="wheel_name left_flag">
        <!-- Wheel geometry -->
        <xacro:wheel_geometry wheel_name="${wheel_name}"/>

        <!-- Wheel attached to base_link -->
        <joint name="${wheel_name}_rolling" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}"/>
            <origin xyz="${-wheel_joint_x} ${wheel_joint_y * left_flag} ${wheel_joint_z}"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <!-- Front wheel function -->
    <xacro:macro name="wheel_front_func" params="wheel_name left_flag">
        <!-- Wheel geometry -->
        <xacro:wheel_geometry wheel_name="${wheel_name}"/>

        <!-- Steering knuckle geometry -->
        <link name="${wheel_name}_steering_knuckle"/>

        <!-- Steering knuckle attached to base_link -->
        <joint name="${wheel_name}_turning" type="revolute">
            <parent link="base_link"/>
            <child link="${wheel_name}_steering_knuckle"/>
            <origin xyz="${wheel_joint_x} ${wheel_joint_y * left_flag} ${wheel_joint_z}"/>
            <axis xyz="0 0 1"/>
            <limit effort="0.0" velocity="0.0" lower="-${PI / 6.0}" upper="${PI / 6.0}" />
        </joint>

        <!-- Wheel attached to steering knuckle -->
        <joint name="${wheel_name}_rolling" type="continuous">
            <parent link="${wheel_name}_steering_knuckle"/>
            <child link="${wheel_name}"/>
            <origin xyz="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>

    <!-- Generate 4 wheels -->
    <xacro:wheel_front_func wheel_name="left_front" left_flag="1"/>
    <xacro:wheel_front_func wheel_name="right_front" left_flag="-1"/>
    <xacro:wheel_rear_func wheel_name="left_rear" left_flag="1"/>
    <xacro:wheel_rear_func wheel_name="right_rear" left_flag="-1"/>
</robot>
